/**
 * traitNames.sync.test.ts — drift gate between the generated
 * `traitNames.ts` static maps and the canonical glossary
 * (`external/fusion-systems-2e/tools/translate-packs/glossary.pt-BR.json`).
 *
 * `traitNames.ts` is GENERATED by `tools/translate-packs/gen-client-maps.mjs`
 * from `glossary.categories.traits` / `glossary.categories.damageTypes`, but
 * nothing previously forced a regeneration when the glossary changed — the
 * generator has to be run BY HAND. That silent drift let the client map fall
 * 27 keys behind the glossary (e.g. `rage` was in the glossary but missing
 * from `TRAIT_NAMES_PT`, so the compendium details popup fell back to a
 * humanized slug instead of the pt-BR label) with no test or CI signal.
 *
 * This test reads the glossary straight off disk and asserts the client maps
 * have the EXACT same key set (`buildMap` in gen-client-maps.mjs copies every
 * glossary key verbatim, only translating values) — any addition/removal on
 * either side without re-running the generator fails here, in the same
 * `pnpm test` (vitest workspace) run the CI "Test" step already executes.
 *
 * F4 (DEC-SEP-09): `tools/translate-packs` moved to the fusion-systems-2e
 * submodule, checked out for real at
 * `external/fusion-systems-2e/tools/translate-packs/` — one path segment
 * deeper than before.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { TRAIT_NAMES_PT, DAMAGE_TYPE_NAMES_PT } from "../traitNames.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const GLOSSARY_PATH = join(
  __dirname,
  "..",
  "..",
  "..",
  "..",
  "..",
  "..",
  "external",
  "fusion-systems-2e",
  "tools",
  "translate-packs",
  "glossary.pt-BR.json",
);

const glossary = JSON.parse(readFileSync(GLOSSARY_PATH, "utf8")) as {
  categories: {
    traits: Record<string, string>;
    damageTypes: Record<string, string>;
  };
};

function diffKeys(actual: string[], expected: string[]) {
  const actualSet = new Set(actual);
  const expectedSet = new Set(expected);
  const missing = expected.filter((k) => !actualSet.has(k));
  const extra = actual.filter((k) => !expectedSet.has(k));
  return { missing, extra };
}

describe("TRAIT_NAMES_PT stays in sync with glossary.categories.traits", () => {
  it("has the same key count as the glossary (regenerate traitNames.ts if this fails)", () => {
    const glossaryCount = Object.keys(glossary.categories.traits).length;
    const generatedCount = Object.keys(TRAIT_NAMES_PT).length;
    expect(
      generatedCount,
      `TRAIT_NAMES_PT has ${generatedCount} keys but the glossary has ${glossaryCount}. ` +
        `Run: node tools/translate-packs/gen-client-maps.mjs`,
    ).toBe(glossaryCount);
  });

  it("has exactly the same keys as the glossary (no missing/extra traits)", () => {
    const { missing, extra } = diffKeys(
      Object.keys(TRAIT_NAMES_PT),
      Object.keys(glossary.categories.traits),
    );
    expect(
      missing,
      `traits in the glossary but missing from TRAIT_NAMES_PT: ${missing.join(", ")}`,
    ).toEqual([]);
    expect(
      extra,
      `traits in TRAIT_NAMES_PT but removed from the glossary: ${extra.join(", ")}`,
    ).toEqual([]);
  });
});

describe("DAMAGE_TYPE_NAMES_PT stays in sync with glossary.categories.damageTypes", () => {
  it("has exactly the same keys as the glossary (no missing/extra damage types)", () => {
    const { missing, extra } = diffKeys(
      Object.keys(DAMAGE_TYPE_NAMES_PT),
      Object.keys(glossary.categories.damageTypes),
    );
    expect(
      missing,
      `damage types in the glossary but missing from DAMAGE_TYPE_NAMES_PT: ${missing.join(", ")}`,
    ).toEqual([]);
    expect(
      extra,
      `damage types in DAMAGE_TYPE_NAMES_PT but removed from the glossary: ${extra.join(", ")}`,
    ).toEqual([]);
  });
});
