/**
 * NPC compendium import → combat initiative — real-pack regression test.
 *
 * WIRING-NPC-PERCEPTION: proves the fix for the M4.5-corretor audit ISSUE
 * ALTA — imported NPCs (both pf2e and sf2e) rolled initiative at a flat
 * "1d20 + 0" because the derivation steps
 * (systems/{pf2e,sf2e}/src/derivations/npc.ts stepNpcPerception) read
 * `system.attributes.perception.mod`, but the REAL packs — generated by
 * tools/importer-pf2e/src/transform.mjs normalizeActorSystem — store
 * perception at the system TOP LEVEL (`system.perception.mod`). The old
 * code silently defaulted to 0 and PERSISTED `derived.perception.total = 0`
 * at compendium-import time (packages/server/src/compendium/service.ts
 * importToWorld), masking the defect from every downstream read.
 *
 * This test boots through the REAL boot() sequence (same pattern as
 * derive-wiring.test.ts / boot-compendium-sf2e.test.ts) with the REAL
 * committed packs on disk (systems/{pf2e,sf2e}/packs/bestiary-core/
 * documents.json — no synthetic fixture), imports a real named NPC
 * (Eagle / Akata, both Perception +6 in the pack), adds it as a combatant,
 * rolls initiative, and asserts:
 *   1. The persisted imported Actor doc has `system.derived.perception.total`
 *      equal to the real statblock mod (6), not 0.
 *   2. The formula string recorded in `roll_audit_log.formula` for that roll
 *      is exactly "1d20 + 6" (the real mod), not "1d20 + 0".
 *
 * 2.942 pre-existing green tests never caught this because every hand-built
 * test fixture across the suite (e2e-dod-m3.test.ts, derivations.test.ts,
 * etc.) manually authors `system.attributes.perception.mod` — the shape the
 * schema *documented* — never the real importer/pack shape. Only a test
 * driven by the actual committed pack data on disk exercises the mismatch.
 *
 * Spec: 17-sistema-pf2e.md REQ-PF2-014/090, 18-sistema-sf2e.md REQ-SF2-014,
 * REQ-CBT-012, DEC-CBT-03.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { io as ioClient } from "socket.io-client";
import type { Socket as ClientSocket } from "socket.io-client";

import { boot } from "../boot.js";
import type { BootResult } from "../boot.js";
import { loadConfig } from "../config.js";
import { createLogger } from "../logger.js";
import { openDatabase, applyMigrations } from "../db/index.js";
import type { FusionDatabase } from "../db/index.js";
import { AuthService } from "../auth/service.js";
import { loadOrCreateSecret } from "../auth/crypto.js";
import { PROTOCOL_VERSION } from "@fusion/shared";
import { pf2eSystem } from "@fusion/system-pf2e";
import { sf2eSystem } from "@fusion/system-sf2e";
import type { SystemModule } from "@fusion/system-api";

// ---------------------------------------------------------------------------
// Test infrastructure (mirrors derive-wiring.test.ts / boot-compendium-sf2e.test.ts)
// ---------------------------------------------------------------------------

function makeTempDir(prefix: string): string {
  const dir = join(
    tmpdir(),
    `fusion-${prefix}-${String(Date.now())}-${Math.random().toString(36).slice(2)}`,
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

interface Ctx {
  dataDir: string;
  fusionDb: FusionDatabase;
  bootResult: BootResult;
  port: number;
  worldId: string;
  gmToken: string;
  gmUserId: string;
}

async function buildCtx(
  worldId: string,
  systemId: string,
  systemModule: SystemModule,
): Promise<Ctx> {
  const dataDir = makeTempDir(worldId);
  const dbPath = join(dataDir, "world.db");

  const secret = loadOrCreateSecret(dataDir);
  const fusionDb = openDatabase({ path: dbPath, skipIntegrityCheck: true });
  applyMigrations(fusionDb.raw, dbPath);

  const authService = new AuthService(fusionDb.raw, secret, worldId);
  const { user: gm, password: gmPw } = await authService.bootstrapGm();
  const gmLogin = await authService.login({ userId: gm.id, password: gmPw, ip: "127.0.0.1" });

  const config = loadConfig({
    dataDirOverride: dataDir,
    cliOverrides: { port: 0, host: "127.0.0.1", logLevel: "silent" },
  });
  const logger = createLogger("silent");

  // Boot through the REAL sequence — packsDir is NOT overridden, so
  // CompendiumService discovers the real committed packs under
  // systems/<systemId>/packs (same resolution boot-compendium*.test.ts
  // relies on). systemModule is supplied so both import-time derivation
  // (compendium/service.ts importToWorld) and the rollInitiative
  // compute-on-read safety net (combat-handlers.ts) are wired.
  const bootResult = await boot({
    config,
    logger,
    skipSignalHandlers: true,
    authContext: {
      worldId,
      worldTitle: `NPC Import Initiative World (${systemId})`,
      worldSystemId: systemId,
      db: fusionDb.raw,
      secret,
    },
    netContext: {
      worldId,
      db: fusionDb.raw,
      secret,
      authService,
      origin: "http://127.0.0.1",
      systemId,
      systemModule,
    },
  });

  const address = bootResult.fastify.server.address();
  if (!address || typeof address === "string") throw new Error("Bad server address");
  const port = address.port;

  return {
    dataDir,
    fusionDb,
    bootResult,
    port,
    worldId,
    gmToken: gmLogin.accessToken,
    gmUserId: gm.id,
  };
}

async function teardown(ctx: Ctx): Promise<void> {
  await ctx.bootResult.shutdown();
  ctx.fusionDb.close();
  rmSync(ctx.dataDir, { recursive: true, force: true });
}

function connectClient(port: number, worldId: string, token: string): ClientSocket {
  return ioClient(`http://127.0.0.1:${String(port)}/world/${worldId}`, {
    auth: { token, protocolVersion: PROTOCOL_VERSION },
    autoConnect: false,
    reconnection: false,
    transports: ["websocket"],
  });
}

function waitForConnect(socket: ClientSocket): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    socket.once("connect", resolve);
    socket.once("connect_error", reject);
  });
}

function sendOp(
  socket: ClientSocket,
  type: string,
  payload: unknown,
): Promise<Record<string, unknown>> {
  return new Promise<Record<string, unknown>>((resolve, reject) => {
    socket.emit("op", { type, ts: Date.now(), payload }, (r: Record<string, unknown>) =>
      resolve(r),
    );
    setTimeout(() => reject(new Error(`Timeout for op: ${type}`)), 8000);
  });
}

function sendQuery(
  socket: ClientSocket,
  type: string,
  payload: unknown,
): Promise<Record<string, unknown>> {
  return new Promise<Record<string, unknown>>((resolve, reject) => {
    socket.emit("query", { type, ts: Date.now(), payload }, (r: Record<string, unknown>) =>
      resolve(r),
    );
    setTimeout(() => reject(new Error(`Timeout for query: ${type}`)), 8000);
  });
}

/**
 * Read the last roll_audit_log row's `formula` column for a given actor.
 *
 * NOTE: InitiativeFormula.roll() (system-formula-adapter.ts) passes
 * `userId: ctx.combatant.actorId ?? ctx.combatant._id` to RollRequest — the
 * roll is attributed to the world Actor id, not the GM's socket userId. We
 * therefore key this lookup on `actor_id`, which the handler also populates
 * (RollRequest.actorId = ctx.combatant.actorId).
 */
function lastRollFormula(fusionDb: FusionDatabase, worldId: string, actorId: string): string {
  const row = fusionDb.raw
    .prepare(
      `SELECT formula FROM roll_audit_log
       WHERE world_id = ? AND actor_id = ?
       ORDER BY created_at DESC, rowid DESC
       LIMIT 1`,
    )
    .get(worldId, actorId) as { formula: string } | undefined;
  if (!row) throw new Error("No roll_audit_log row found");
  return row.formula;
}

// ---------------------------------------------------------------------------
// Shared scenario runner — bestiaryPackId + npcName + expected mod are the
// only per-system knobs; the rest of the flow (import → combat → roll →
// assert) is identical for pf2e and sf2e (REQ-SF2-004: identical formulas).
// ---------------------------------------------------------------------------

interface Scenario {
  worldId: string;
  systemId: string;
  systemModule: SystemModule;
  bestiaryPackId: string;
  npcName: string;
  expectedPerceptionMod: number;
}

function runScenario(scenario: Scenario): void {
  const { worldId, systemId, systemModule, bestiaryPackId, npcName, expectedPerceptionMod } =
    scenario;

  describe(`NPC import → initiative roll uses the real Perception mod (${systemId}, ${npcName})`, () => {
    let ctx: Ctx;
    let gm: ClientSocket;

    beforeAll(async () => {
      ctx = await buildCtx(worldId, systemId, systemModule);
      gm = connectClient(ctx.port, ctx.worldId, ctx.gmToken);
      gm.connect();
      await waitForConnect(gm);
    }, 30000);

    afterAll(async () => {
      gm?.disconnect();
      await teardown(ctx);
    });

    it(`imports the real ${npcName} from the committed bestiary pack with derived.perception.total = ${String(expectedPerceptionMod)}`, async () => {
      const indexAck = await sendQuery(gm, "compendium:index", { packId: bestiaryPackId });
      expect(indexAck["ok"]).toBe(true);
      const entries = (indexAck["result"] as { entries: Array<{ uuid: string; name: string }> })
        .entries;
      const npcEntry = entries.find((e) => e.name === npcName);
      expect(npcEntry).toBeDefined();

      // Sanity: the pack's raw statblock really does carry the non-zero mod
      // this test expects (guards against the pack itself changing silently).
      const getAck = await sendQuery(gm, "compendium:get", { uuid: npcEntry!.uuid });
      expect(getAck["ok"]).toBe(true);
      const packDoc = (getAck["result"] as { document: Record<string, unknown> }).document;
      const packSys = packDoc["system"] as Record<string, unknown>;
      const packPerception = packSys["perception"] as Record<string, unknown> | undefined;
      expect(packPerception?.["mod"]).toBe(expectedPerceptionMod);

      const importAck = await sendOp(gm, "compendium:import", { uuids: [npcEntry!.uuid] });
      expect(importAck["ok"]).toBe(true);
      const importResult = importAck["result"] as { created: string[]; failed: unknown[] };
      expect(importResult.failed).toEqual([]);
      expect(importResult.created.length).toBe(1);
      const actorId = importResult.created[0]!;

      // ASSERT: derived.perception.total was correctly computed and
      // PERSISTED at import time — this is the field the old bug left at 0.
      const actor = ctx.fusionDb.raw
        .prepare(`SELECT data FROM actors WHERE id = ?`)
        .get(actorId) as { data: string } | undefined;
      expect(actor).toBeDefined();
      const actorDoc = JSON.parse(actor!.data) as Record<string, unknown>;
      const actorSys = actorDoc["system"] as Record<string, unknown>;
      const derived = actorSys["derived"] as Record<string, unknown> | undefined;
      expect(derived).toBeDefined();
      const derivedPerception = derived!["perception"] as { total: number } | undefined;
      expect(derivedPerception?.total).toBe(expectedPerceptionMod);

      // Create a combat + combatant for this actor, then roll initiative.
      const sceneAck = await sendOp(gm, "doc:create", {
        documentType: "Scene",
        data: [
          {
            name: `${systemId} Initiative Scene`,
            grid: { type: "square", size: 100 },
            active: false,
            width: 1000,
            height: 1000,
            ownership: { default: 2 },
          },
        ],
      });
      expect(sceneAck["ok"]).toBe(true);
      const sceneId = (sceneAck["result"] as { documents: Array<{ _id: string }> }).documents[0]!
        ._id;

      const combatAck = await sendOp(gm, "combat:create", { sceneId });
      expect(combatAck["ok"]).toBe(true);
      const combatId = (combatAck["result"] as { combat: { _id: string } }).combat._id;

      const addAck = await sendOp(gm, "combat:addCombatant", {
        combatId,
        tokenId: `synthetic-token-${npcName}`,
        actorId,
        hidden: false,
      });
      expect(addAck["ok"]).toBe(true);
      const combatantId = (addAck["result"] as { combatant: { _id: string } }).combatant._id;

      const rollAck = await sendOp(gm, "combat:rollInitiative", {
        combatId,
        combatantIds: [combatantId],
      });
      expect(rollAck["ok"]).toBe(true);
      const rollResult = rollAck["result"] as {
        combat: { combatants: Array<{ _id: string; initiative: number | null }> };
        rolledCount: number;
      };
      expect(rollResult.rolledCount).toBe(1);
      const rolledCombatant = rollResult.combat.combatants.find((c) => c._id === combatantId);
      expect(rolledCombatant).toBeDefined();
      expect(typeof rolledCombatant!.initiative).toBe("number");

      // THE KEY ASSERTION: the formula persisted in roll_audit_log must be
      // "1d20 + <real mod>", never "1d20 + 0". This is the exact roll
      // executed server-side (DEC-CBT-03 authoritative), keyed by actor_id
      // (see lastRollFormula docstring).
      const formula = lastRollFormula(ctx.fusionDb, worldId, actorId);
      expect(formula).toBe(`1d20 + ${String(expectedPerceptionMod)}`);
    });
  });
}

// ---------------------------------------------------------------------------
// Suites
// ---------------------------------------------------------------------------

runScenario({
  worldId: "npc_import_initiative_pf2e",
  systemId: "pf2e",
  systemModule: pf2eSystem,
  bestiaryPackId: "pf2e.bestiary-core",
  npcName: "Eagle",
  expectedPerceptionMod: 6,
});

runScenario({
  worldId: "npc_import_initiative_sf2e",
  systemId: "sf2e",
  systemModule: sf2eSystem,
  bestiaryPackId: "sf2e.bestiary-core",
  npcName: "Akata",
  expectedPerceptionMod: 6,
});
