/**
 * Installation-level admin HTTP routes for @fusion/server (M6/B2).
 *
 * Routes (all under /admin/*, REQ-DST-015A plan 1 — Admin Key, NOT the
 * world-user GAMEMASTER plane served under /api/*):
 *
 *   GET  /admin/setup/state   — public (pre- and post-setup): what the
 *                                wizard needs to render (defaults, current
 *                                values, LAN URLs). Never leaks the Admin
 *                                Key hash or jwtHmacSecret.
 *   POST /admin/setup/check-port — public: { port } -> { available, suggestion? }
 *                                (REQ-DST-015, checked live as the GM types).
 *   POST /admin/setup/apply   — first run: open (no Bearer required, since
 *                                there is no Admin Key yet to present).
 *                                Re-run (REQ-DST-014, "Reconfigurar"):
 *                                requires a valid admin Bearer token.
 *   GET  /admin/network       — requires Bearer; LAN URLs + QR-ready data +
 *                                a `tunnel` field the M6/B4 batch will fill
 *                                in (see the field's doc comment for the
 *                                agreed shape).
 *
 * Guard rule (REQ-DST-011/014): while setupCompleted is false, ALL /admin/*
 * routes are reachable without a Bearer (there is nothing to authenticate
 * against yet — the wizard IS the bootstrap). The instant setupCompleted
 * flips to true, every /admin/* route (including a fresh /admin/setup/apply
 * re-run) requires `Authorization: Bearer <admin token>` verified against
 * the persisted jwtHmacSecret. This is enforced by requireAdminAuth below,
 * registered as a per-route preHandler (not a blanket onRequest hook) so
 * pre-setup callers are never asked for a Bearer. Two read-only routes
 * (`/admin/setup/state`, `/admin/setup/check-port`) additionally stay
 * reachable WITHOUT a Bearer post-setup for the wizard's own re-run first
 * load, but see their individual route comments below for exactly what each
 * degrades to when unauthenticated post-setup.
 *
 * `/admin/login` (REQ-SEC-011): brute-force lockout by IP, reusing
 * auth/lockout.ts's LockoutStore against a dedicated admin-plane SQLite file
 * (see lockout-db.ts) — same policy/parameters as the world-user login
 * plane (5 failures / 15 min).
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { z } from "zod";
import type { Logger } from "pino";
import {
  applySetup,
  buildLanInviteUrls,
  isFirstRun,
  isPortAvailable,
  findAvailablePort,
  resolvePortableDataDir,
  signAdminToken,
  verifyAdminKey,
  verifyAdminToken,
  type SetupState,
} from "./service.js";
import { createDesktopShortcut } from "./desktop-shortcut.js";
import { openAdminLockoutDb, ADMIN_LOCKOUT_SUBJECT } from "./lockout-db.js";
import { LockoutStore } from "../auth/lockout.js";
import { loadConfig, resolveDefaultDataDir, type ServerConfig } from "../config.js";

// ---------------------------------------------------------------------------
// Config accessor — routes always re-read the live Config/fusion.json so a
// completed setup (or a reconfiguration) is reflected on the very next
// request without requiring a process restart to pick up the auth guard.
// ---------------------------------------------------------------------------

function readLiveConfig(dataDir: string): ServerConfig {
  return loadConfig({ dataDirOverride: dataDir });
}

/**
 * Resolve "the port this server is currently serving from" for the
 * self-conflict special-cases (check-port, apply, setup/state, network) AND
 * for every URL/QR surface the GM is meant to actually use right now
 * (lan.urls, /admin/setup/state's lanUrls).
 *
 * ALWAYS returns `currentPort` — the boot-time runtime value this process is
 * actually bound to (config.port as resolved by boot.ts's CLI/env/file/
 * default layering, see RegisterAdminRoutesOptions). This is deliberate even
 * after setup has completed at least once: `applySetup` persists the GM's
 * newly-chosen port to Config/fusion.json immediately, but REQ-DST-013 says
 * that port only takes effect on the NEXT boot — the HTTP listener already
 * bound to `currentPort` for this process's lifetime. Preferring the disk
 * value here (as an earlier version of this function did) produced a live
 * bug: with an explicit `--port` different from the persisted value (e.g.
 * disk has 33661 from a prior apply, this boot was started with
 * `--port 33663`), every LAN URL / QR code generated by this function would
 * point at 33661 — a port nothing is listening on — AND `check-port`'s
 * self-conflict special-case would compare an incoming probe of 33663 (the
 * REAL bound port) against 33661, fail to recognize it as "this server's own
 * port", report it as available, and let a subsequent `apply` on 33663
 * collide with itself and return 409. See `configuredPortNextBoot` below for
 * surfacing the disk value explicitly to callers that need it (e.g. a wizard
 * confirming "your reconfiguration will take effect after a restart").
 */
function resolveCurrentPort(_config: ServerConfig, currentPort: number): number {
  return currentPort;
}

/**
 * The port PERSISTED on disk (Config/fusion.json), which takes effect only
 * on the NEXT boot (REQ-DST-013) — distinct from `resolveCurrentPort`'s
 * boot-time value. Named explicitly (not just "config.port") so call sites
 * can never confuse "port this process is bound to right now" with "port a
 * completed/reconfigured setup will use after a restart". Falls back to
 * `currentPort` pre-setup (isFirstRun): before the first apply, the disk has
 * no persisted port at all and the zod schema default (33000) would be
 * misleading — "next boot" is meaningless until setup has completed once.
 */
function resolveConfiguredPortNextBoot(config: ServerConfig, currentPort: number): number {
  return isFirstRun(config) ? currentPort : config.port;
}

// ---------------------------------------------------------------------------
// Bearer admin guard
// ---------------------------------------------------------------------------

function extractBearer(request: FastifyRequest): string | null {
  const header = request.headers.authorization;
  if (typeof header !== "string") return null;
  const match = /^Bearer\s+(.+)$/i.exec(header);
  return match?.[1] ?? null;
}

/**
 * Resolve the client IP for lockout tracking. Mirrors auth/routes.ts's
 * clientIp exactly (kept as a local copy rather than exported/shared since
 * that module scopes it as a route-registration-local closure over
 * `trustProxy` — duplicating four lines here is simpler than restructuring
 * that module's exports for a single reuse site): without a trusted
 * TLS-terminating proxy in front (config.trustProxy), X-Forwarded-For is
 * attacker-controlled and rotating it must NOT reset the lockout counter.
 */
function clientIp(request: FastifyRequest, trustProxy: boolean): string {
  if (trustProxy) {
    return request.ip;
  }
  return request.socket.remoteAddress ?? request.ip;
}

/**
 * Build a Fastify preHandler enforcing the guard rule described in the
 * module doc comment: no auth required until setupCompleted, Bearer admin
 * token required after. `dataDir` is captured once at route-registration
 * time (matches every other route module in this codebase — data dir is
 * fixed for the lifetime of a boot).
 */
/**
 * Exported for reuse by other /admin/* route modules registered on the same
 * Fastify instance (e.g. M6/B4's tunnel/routes.ts, which registers
 * POST /admin/network/tunnel under the same auth guard as GET /admin/network
 * above — both are part of the same "installation admin plane").
 */
export function requireAdminAuth(dataDir: string) {
  return async (request: FastifyRequest, reply: FastifyReply): Promise<void> => {
    const config = readLiveConfig(dataDir);

    if (isFirstRun(config)) {
      return; // no Admin Key exists yet — wizard bootstrap is inherently open
    }

    const token = extractBearer(request);
    if (token === null || config.jwtHmacSecret === undefined) {
      await reply
        .code(401)
        .send({ ok: false, code: "UNAUTHORIZED", message: "Admin Bearer token required." });
      return;
    }

    const valid = await verifyAdminToken(token, config.jwtHmacSecret);
    if (!valid) {
      await reply
        .code(401)
        .send({ ok: false, code: "UNAUTHORIZED", message: "Invalid or expired admin token." });
      return;
    }
  };
}

// ---------------------------------------------------------------------------
// Request body schemas
// ---------------------------------------------------------------------------

const CheckPortBodySchema = z.object({
  port: z.number().int().min(1024).max(65535),
});

const ApplySetupBodySchema = z.object({
  dataDir: z.string().min(1),
  port: z.number().int().min(1024).max(65535),
  adminKey: z.string().min(8).max(256),
});

const LoginBodySchema = z.object({
  adminKey: z.string().min(1),
});

// ---------------------------------------------------------------------------
// /admin/network response shape (contract with M6/B4 — the tunnel batch)
// ---------------------------------------------------------------------------

/**
 * Shape agreed with M6/B4 (`fusion serve --tunnel`, cloudflared):
 *   - `lan`: always populated by THIS batch (B2) — LAN IPs + port.
 *   - `tunnel`: always present as a key so clients never need an `in`
 *     check, but its value is `null` until B4 lands. B4 fills it with
 *     `{ enabled: boolean, url: string | null, provider: "cloudflared" }`
 *     once the child-process/tunnel manager exists. Documented here so B4
 *     does not have to renegotiate the response envelope.
 */
export interface AdminNetworkResponse {
  lan: {
    port: number;
    urls: string[];
  };
  tunnel: { enabled: boolean; url: string | null; provider: "cloudflared" } | null;
}

// ---------------------------------------------------------------------------
// Route registration
// ---------------------------------------------------------------------------

export interface RegisterAdminRoutesOptions {
  dataDir: string;
  logger?: Logger;
  /**
   * The port THIS process is actually bound to for this boot (config.port as
   * resolved by boot.ts, i.e. after CLI --port / env / fusion.json / default
   * layering — see config.ts's loadConfig precedence). Required so the
   * self-port special-cases below (check-port, apply, setup/state,
   * /admin/network's lan.port) compare against reality instead of
   * re-reading Config/fusion.json from disk, which only reflects a port
   * once a completed setup has persisted one — before that (fresh install
   * booted with an explicit --port), the file has no `port` key and
   * readLiveConfig() falls back to the schema default (33000), which is
   * wrong whenever the operator's --port differs from 33000. All other
   * fields (setupCompleted, adminPasswordHash, jwtHmacSecret) still come
   * from readLiveConfig() so a completed setup/reconfiguration is reflected
   * live without a restart — only "which port is this process on" needs the
   * boot-time value.
   */
  currentPort: number;
  /**
   * M6/B4 integration point: when provided, GET /admin/network's `tunnel`
   * field reflects this manager's live state instead of always being `null`.
   * Optional so admin routes keep working standalone (e.g. tests, or a boot
   * where --tunnel was never requested) without importing tunnel/ at all.
   */
  getTunnelState?: () => { enabled: boolean; url: string | null; provider: "cloudflared" };
}

export function registerAdminRoutes(
  fastify: FastifyInstance,
  options: RegisterAdminRoutesOptions,
): void {
  const { dataDir, logger, currentPort, getTunnelState } = options;
  const authGuard = requireAdminAuth(dataDir);

  // REQ-SEC-011: brute-force lockout for /admin/login, reusing LockoutStore
  // (auth/lockout.ts) against a dedicated admin-plane SQLite file — see
  // lockout-db.ts's module doc comment for why this cannot reuse a world db.
  // Opened once per boot and kept open for the process's lifetime, matching
  // every other long-lived DB handle in this codebase.
  const lockoutDb = openAdminLockoutDb(dataDir);
  const adminLockouts = new LockoutStore(lockoutDb.raw);
  fastify.addHook("onClose", (_instance, done) => {
    lockoutDb.close();
    done();
  });

  // -------------------------------------------------------------------------
  // GET /admin/setup/state
  //
  // Pre-setup: always open (no Bearer to present yet — the wizard IS the
  // bootstrap). Post-setup: requires Bearer, EXCEPT the response degrades to
  // a minimal `{ setupCompleted: true }` body when no valid Bearer is
  // presented instead of a hard 401 — the client's own boot-time router
  // needs to know "is setup done?" (to decide whether to render the app
  // shell or redirect to /setup) before it has ever obtained an admin token.
  // Everything else in the full state (currentDataDir — a filesystem path
  // that leaks the OS username on Windows/macOS/Linux home dirs —, LAN IPs,
  // serverVersion) is installation-topology information with no legitimate
  // use for an unauthenticated caller reaching this endpoint over a public
  // tunnel URL, so it is withheld rather than degraded.
  // -------------------------------------------------------------------------
  fastify.get("/admin/setup/state", async (request, reply) => {
    const config = readLiveConfig(dataDir);

    if (!isFirstRun(config)) {
      const token = extractBearer(request);
      const valid =
        token !== null &&
        config.jwtHmacSecret !== undefined &&
        (await verifyAdminToken(token, config.jwtHmacSecret));
      if (!valid) {
        return reply.send({ ok: true, state: { setupCompleted: true } });
      }
    }

    const resolvedPort = resolveCurrentPort(config, currentPort);
    const state: SetupState = {
      setupCompleted: config.setupCompleted,
      defaultDataDir: resolveDefaultDataDir(),
      portableDataDir: resolvePortableDataDir(),
      currentDataDir: config.dataDir,
      currentPort: resolvedPort,
      configuredPortNextBoot: resolveConfiguredPortNextBoot(config, currentPort),
      lanUrls: buildLanInviteUrls(resolvedPort),
      serverVersion: config.serverVersion ?? "unknown",
    };
    return reply.send({ ok: true, state });
  });

  // -------------------------------------------------------------------------
  // POST /admin/setup/check-port — REQ-DST-015, checked live as the GM types.
  //
  // Pre-setup: open (the wizard's own first-load port check). Post-setup:
  // requires Bearer — without this guard, anyone with the tunnel URL could
  // use this endpoint as a free port-scan oracle against the GM's host
  // (probing arbitrary ports and learning what is bound there), which has no
  // legitimate use once the wizard itself is no longer reachable.
  // -------------------------------------------------------------------------
  fastify.post("/admin/setup/check-port", { preHandler: authGuard }, async (request, reply) => {
    const parsed = CheckPortBodySchema.safeParse(request.body);
    if (!parsed.success) {
      return reply
        .code(400)
        .send({ ok: false, code: "VALIDATION_ERROR", message: "Invalid port." });
    }

    const { port } = parsed.data;

    // The port THIS server is currently bound to will always fail a raw
    // bind-probe (something is already listening on it — this process!).
    // Report it as available so the wizard does not show "port in use" for
    // the server's own current port on every load — see applySetup's own
    // "port !== resolveCurrentPort(...)" special-case for the same
    // reasoning, applied here so the live indicator matches what apply()
    // will actually accept without a conflict. See resolveCurrentPort's doc
    // comment for why this is not simply readLiveConfig(dataDir).port.
    const config = readLiveConfig(dataDir);
    if (port === resolveCurrentPort(config, currentPort)) {
      return reply.send({ ok: true, available: true });
    }

    const available = await isPortAvailable(port);
    if (available) {
      return reply.send({ ok: true, available: true });
    }

    const suggestion = await findAvailablePort(port + 1);
    return reply.send({ ok: true, available: false, suggestion });
  });

  // -------------------------------------------------------------------------
  // POST /admin/setup/apply — first run: open. Re-run: Bearer required.
  // -------------------------------------------------------------------------
  fastify.post("/admin/setup/apply", { preHandler: authGuard }, async (request, reply) => {
    const parsed = ApplySetupBodySchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.code(400).send({
        ok: false,
        code: "VALIDATION_ERROR",
        message: parsed.error.issues.map((i) => i.message).join("; "),
      });
    }

    const { dataDir: chosenDataDir, port, adminKey } = parsed.data;

    // REQ-DST-015: re-validate port availability server-side even though
    // the wizard checked live — a race (another process grabbed it between
    // the last check-port call and submit) must not silently misconfigure.
    // Exception: the port currently in use BY THIS SERVER is fine to keep
    // (re-applying the same port on a reconfiguration is not a conflict).
    // See resolveCurrentPort's doc comment for why this is not simply
    // readLiveConfig(dataDir).port.
    const configBeforeApply = readLiveConfig(dataDir);
    const portBeforeApply = resolveCurrentPort(configBeforeApply, currentPort);
    if (port !== portBeforeApply) {
      const available = await isPortAvailable(port);
      if (!available) {
        const suggestion = await findAvailablePort(port + 1);
        return reply.code(409).send({
          ok: false,
          code: "PORT_IN_USE",
          message: `Port ${String(port)} is already in use.`,
          suggestion,
        });
      }
    }

    const result = await applySetup(dataDir, { dataDir: chosenDataDir, port, adminKey });
    logger?.info({ dataDir: chosenDataDir, port }, "Setup wizard applied — setupCompleted=true");

    // REQ-DST-013: the port only takes effect on next boot (the HTTP
    // listener already bound the OLD port for this process). Surface that
    // explicitly rather than silently pretending a live port switch
    // happened — restarting a listening Fastify server mid-request is
    // unsafe. dataDir changes also require a restart (worlds/systems were
    // already resolved against the old path at boot time).
    const restartRequired = port !== portBeforeApply || result.dataDirChanged;

    return reply.send({
      ok: true,
      adminToken: result.adminToken,
      lanUrls: result.lanUrls,
      restartRequired,
    });
  });

  // -------------------------------------------------------------------------
  // POST /admin/login — re-authenticate with the Admin Key to obtain a new
  // Bearer token (REQ-DST-014's "Reconfigurar" entry point needs this: the
  // GM re-opens /setup after the token from the initial apply has expired
  // or was never stored client-side across a browser restart).
  //
  // REQ-SEC-011 / design doc §3.3 (prerequisite for exposing the server to
  // the internet via --tunnel): max 5 failed attempts per IP in 15 minutes,
  // then 429 with Retry-After — same policy as the world-user login plane
  // (auth/routes.ts), via the SAME LockoutStore implementation. Checked
  // BEFORE any credential comparison to avoid a timing oracle, exactly as
  // auth/service.ts's login() does.
  // -------------------------------------------------------------------------
  fastify.post("/admin/login", async (request, reply) => {
    const config = readLiveConfig(dataDir);
    if (isFirstRun(config) || config.adminPasswordHash === undefined) {
      return reply.code(409).send({
        ok: false,
        code: "SETUP_NOT_COMPLETED",
        message: "No Admin Key configured yet — run the setup wizard first.",
      });
    }

    const ip = clientIp(request, config.trustProxy);
    const lockoutUntil = adminLockouts.checkLockout({ userId: ADMIN_LOCKOUT_SUBJECT, ip });
    if (lockoutUntil !== null) {
      const retryAfterSec = Math.max(1, Math.ceil((lockoutUntil.getTime() - Date.now()) / 1000));
      void reply.header("Retry-After", String(retryAfterSec));
      return reply.code(429).send({
        ok: false,
        code: "LOCKED_OUT",
        message: "Too many failed login attempts. Please try again later.",
      });
    }

    const parsed = LoginBodySchema.safeParse(request.body);
    if (!parsed.success) {
      return reply
        .code(400)
        .send({ ok: false, code: "VALIDATION_ERROR", message: "Admin Key required." });
    }

    const valid = await verifyAdminKey(parsed.data.adminKey, config.adminPasswordHash);
    if (!valid || config.jwtHmacSecret === undefined) {
      adminLockouts.record({ userId: ADMIN_LOCKOUT_SUBJECT, ip, success: false });
      return reply
        .code(401)
        .send({ ok: false, code: "INVALID_CREDENTIALS", message: "Invalid Admin Key." });
    }

    adminLockouts.clearFailures({ userId: ADMIN_LOCKOUT_SUBJECT, ip });
    const adminToken = await signAdminToken(config.jwtHmacSecret);
    return reply.send({ ok: true, adminToken });
  });

  // -------------------------------------------------------------------------
  // POST /admin/setup/desktop-shortcut — REQ-DST-016/017, opt-in button.
  // Requires Bearer once setup is completed (first-run flow can also call it
  // right after apply, using the token apply() just returned).
  // -------------------------------------------------------------------------
  fastify.post("/admin/setup/desktop-shortcut", { preHandler: authGuard }, (_request, reply) => {
    const config = readLiveConfig(dataDir);
    const result = createDesktopShortcut({
      dataDir: config.dataDir,
      port: resolveCurrentPort(config, currentPort),
      execPath: process.execPath,
    });
    return reply.code(result.ok ? 200 : 400).send({ ok: result.ok, message: result.message });
  });

  // -------------------------------------------------------------------------
  // GET /admin/network — requires Bearer once setup is completed
  // -------------------------------------------------------------------------
  fastify.get("/admin/network", { preHandler: authGuard }, (_request, reply) => {
    const resolvedPort = resolveCurrentPort(readLiveConfig(dataDir), currentPort);
    const response: AdminNetworkResponse = {
      lan: {
        port: resolvedPort,
        urls: buildLanInviteUrls(resolvedPort),
      },
      // M6/B4: populated when a TunnelManager was wired in via
      // getTunnelState (see RegisterAdminRoutesOptions); null otherwise
      // (tunnel feature not requested for this boot, e.g. no --tunnel flag).
      tunnel: getTunnelState ? getTunnelState() : null,
    };
    return reply.send({ ok: true, ...response });
  });
}
