/**
 * traitNames.ts — GENERATED. Do not edit by hand.
 *
 * Static EN→pt-BR display maps for the compendium details popup
 * (DocumentDetailsPanel): trait chips, damage types, tradition/rarity/area
 * labels. Generated from tools/translate-packs/glossary.pt-BR.json with
 * orthographic accent corrections (the glossary stores ASCII-folded values
 * for its deterministic substitution pipeline).
 *
 * Regenerate: node tools/translate-packs/gen-client-maps.mjs
 *
 * Lookups are locale-gated by the caller (EN locale shows the raw slug);
 * an unknown slug falls back to a humanized form of the slug itself.
 */

/**
 * Trait slug → pt-BR chip label (248 traits).
 */
export const TRAIT_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  aberration: "aberração",
  acid: "ácido",
  additive: "aditivo",
  additive1: "aditivo1",
  additive2: "aditivo2",
  adjustment: "ajuste",
  agile: "ágil",
  air: "ar",
  alchemical: "alquímico",
  alchemist: "alquimista",
  amp: "amplificado",
  anadi: "anadi",
  android: "androide",
  animal: "animal",
  animist: "animista",
  apparition: "aparição",
  arcane: "arcano",
  archetype: "arquétipo",
  ardande: "ardande",
  attack: "ataque",
  auditory: "auditivo",
  aura: "aura",
  automaton: "autômato",
  azarketi: "azarketi",
  backstabber: "traiçoeiro",
  barbarian: "bárbaro",
  bard: "bardo",
  bomb: "bomba",
  brandish: "brandir",
  bravado: "bravata",
  bulwark: "bastião",
  cantrip: "truque",
  catfolk: "felido",
  centaur: "centauro",
  champion: "campeão",
  circus: "circo",
  class: "classe",
  cleric: "clérigo",
  cold: "frio",
  commander: "comandante",
  composite: "composto",
  composition: "composição",
  concentrate: "concentração",
  conrasu: "conrasu",
  consecration: "consagração",
  consumable: "consumível",
  contact: "contato",
  contingency: "contingência",
  curse: "maldição",
  cursebound: "atado-à-maldição",
  darkness: "escuridão",
  "deadly-d10": "letal-d10",
  "deadly-d8": "letal-d8",
  death: "morte",
  dedication: "dedicação",
  detection: "detecção",
  disarm: "desarmar",
  disease: "doença",
  divine: "divino",
  downtime: "tempo-livre",
  dragonet: "dragonete",
  druid: "druida",
  duergar: "duergar",
  dwarf: "anão",
  earth: "terra",
  eidolon: "eidolon",
  electricity: "eletricidade",
  elf: "elfo",
  elixir: "elixir",
  emotion: "emoção",
  "entrench-ranged": "entrincheiramento-distância",
  esoterica: "esotérica",
  evil: "maligno",
  evolution: "evolução",
  exemplar: "exemplar",
  expandable: "expansível",
  exploration: "exploração",
  extradimensional: "extradimensional",
  fear: "medo",
  fighter: "guerreiro",
  finesse: "precisão",
  finisher: "finalização",
  fire: "fogo",
  fleshwarp: "disforme",
  flexible: "flexível",
  flourish: "floreio",
  focus: "foco",
  force: "força",
  forceful: "vigoroso",
  fortune: "sorte",
  "free-hand": "mão-livre",
  fungus: "fungo",
  general: "geral",
  ghoran: "ghoran",
  gnome: "gnomo",
  goblin: "goblin",
  goloma: "goloma",
  good: "benigno",
  guardian: "guardião",
  gunslinger: "pistoleiro",
  halfling: "halfling",
  healing: "cura",
  hex: "bruxaria",
  holy: "sagrado",
  human: "humano",
  humanoid: "humanoide",
  ikon: "ícone",
  illusion: "ilusão",
  impulse: "impulso",
  incapacitation: "incapacitação",
  incarnate: "encarnado",
  infused: "infundido",
  infusion: "infusão",
  ingested: "ingerido",
  inhaled: "inalado",
  injury: "ferimento",
  inventor: "inventor",
  invested: "investido",
  investigator: "investigador",
  jotunborn: "jotunborn",
  kholo: "kholo",
  kineticist: "cineticista",
  kobold: "kobold",
  laminar: "laminado",
  leshy: "leshy",
  light: "luz",
  lineage: "linhagem",
  linguistic: "linguístico",
  lizardfolk: "reptiliano",
  lozenge: "pastilha",
  magical: "mágico",
  magus: "magus",
  manipulate: "manipulação",
  mental: "mental",
  metal: "metal",
  mindless: "sem-mente",
  mindshift: "mudança-de-mente",
  minotaur: "minotauro",
  misfortune: "azar",
  modification: "modificação",
  monk: "monge",
  morph: "metamorfose",
  move: "movimento",
  multiclass: "multiclasse",
  mutagen: "mutágeno",
  mythic: "mítico",
  naari: "naari",
  nephilim: "nefilim",
  noisy: "barulhento",
  nonlethal: "não-letal",
  oath: "voto",
  occult: "oculto",
  oil: "óleo",
  olfactory: "olfativo",
  oracle: "oráculo",
  orc: "orc",
  oread: "oréade",
  overflow: "transbordamento",
  parry: "aparar",
  plant: "planta",
  poison: "veneno",
  polymorph: "transmutação",
  ponderous: "vagaroso",
  poppet: "marionete",
  potion: "poção",
  prediction: "previsão",
  press: "pressão",
  primal: "primal",
  processed: "processado",
  propulsive: "propulsivo",
  psyche: "psique",
  psychic: "psíquico",
  rage: "fúria",
  ranger: "patrulheiro",
  ratfolk: "ratkin",
  reach: "alcance",
  "reach-10": "alcance-10",
  reckless: "imprudente",
  "reload-0": "recarga-0",
  "reload-1": "recarga-1",
  revelation: "revelação",
  rogue: "ladino",
  samsaran: "samsaran",
  sanctified: "santificado",
  sarangay: "sarangay",
  scrying: "vidência",
  secret: "secreto",
  shadow: "sombra",
  shisk: "shisk",
  shoony: "shoony",
  shove: "empurrar",
  skeleton: "esqueleto",
  skill: "perícia",
  sleep: "sono",
  social: "social",
  sonic: "sônico",
  sorcerer: "feiticeiro",
  spellshape: "moldar-magia",
  spellshot: "tiro-magico",
  spirit: "espírito",
  splash: "respingo",
  sprite: "sprite",
  stamina: "vigor",
  stance: "postura",
  strix: "strix",
  structure: "estrutura",
  subtle: "sutil",
  suli: "suli",
  summon: "convocação",
  summoner: "conjurador",
  swashbuckler: "espadachim",
  sweep: "varredura",
  sylph: "sílfide",
  tactic: "tática",
  talisman: "talismã",
  talos: "talos",
  tandem: "conjunto",
  teleportation: "teleporte",
  tengu: "tengu",
  thaumaturge: "taumaturgo",
  thrown: "arremesso",
  "thrown-10": "arremesso-10",
  "thrown-20": "arremesso-20",
  "thrown-30": "arremesso-30",
  transcendence: "transcendência",
  trip: "derrubar",
  tripkee: "tripkee",
  "true-name": "nome-verdadeiro",
  "two-hand-d12": "duas-mãos-d12",
  "two-hand-d8": "duas-mãos-d8",
  unarmed: "desarmado",
  undead: "morto-vivo",
  undine: "ondina",
  unholy: "profano",
  unstable: "instável",
  "versatile-p": "versátil-p",
  "versatile-s": "versátil-c",
  virulent: "virulento",
  visual: "visual",
  vitality: "vitalidade",
  void: "vazio",
  "volley-30": "salva-30",
  wandering: "errante",
  water: "água",
  witch: "bruxo",
  wizard: "mago",
  wood: "madeira",
  zombie: "zumbi",
});

/**
 * Damage-type slug → pt-BR.
 */
export const DAMAGE_TYPE_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  acid: "ácido",
  bleed: "sangramento",
  bludgeoning: "concussão",
  cold: "frio",
  electricity: "eletricidade",
  fire: "fogo",
  force: "força",
  mental: "mental",
  piercing: "perfuração",
  poison: "veneno",
  precision: "precisão",
  slashing: "corte",
  sonic: "sônico",
  spirit: "espírito",
  untyped: "sem tipo",
  vitality: "vitalidade",
  void: "vazio",
});

/**
 * Magic tradition slug → pt-BR.
 */
export const TRADITION_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  arcane: "Arcana",
  divine: "Divina",
  occult: "Oculta",
  primal: "Primal",
});

/**
 * Rarity slug → pt-BR.
 */
export const RARITY_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  common: "Comum",
  rare: "Raro",
  uncommon: "Incomum",
  unique: "Único",
});

/**
 * Area-template shape slug → pt-BR.
 */
export const AREA_SHAPE_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  burst: "explosão",
  cone: "cone",
  cube: "cubo",
  cylinder: "cilindro",
  emanation: "emanação",
  line: "linha",
  square: "quadrado",
});
