/**
 * traitNames.ts — GENERATED. Do not edit by hand.
 *
 * Static EN→pt-BR display maps for the compendium details popup
 * (DocumentDetailsPanel): trait chips, damage types, tradition/rarity/area
 * labels. Generated from tools/translate-packs/glossary.pt-BR.json with
 * orthographic accent corrections (the glossary stores ASCII-folded values
 * for its deterministic substitution pipeline).
 *
 * Regenerate: node tools/translate-packs/gen-client-maps.mjs
 *
 * Lookups are locale-gated by the caller (EN locale shows the raw slug);
 * an unknown slug falls back to a humanized form of the slug itself.
 */

/**
 * Trait slug → pt-BR chip label (333 traits).
 */
export const TRAIT_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  aberration: "aberração",
  acid: "ácido",
  adamantine: "adamantina",
  aeon: "eon",
  agile: "ágil",
  air: "ar",
  aiuvarin: "aiuvarin",
  alchemical: "alquimico",
  alchemist: "alquimista",
  amp: "amplificação",
  amphibious: "anfibio",
  anadi: "anadi",
  android: "androide",
  angel: "anjo",
  animal: "animal",
  animist: "animista",
  aquatic: "aquatico",
  arcane: "arcano",
  archetype: "arquétipo",
  archon: "arconte",
  ardande: "ardande",
  artifact: "artefato",
  astral: "astral",
  attack: "ataque",
  auditory: "auditivo",
  aura: "aura",
  automaton: "autômato",
  azarketi: "azarketi",
  azata: "azata",
  backstabber: "traiçoeiro",
  backswing: "golpe-de-retorno",
  barbarian: "bárbaro",
  bard: "bardo",
  beast: "besta",
  boggard: "boggard",
  brandish: "brandir",
  bravado: "bravata",
  brutal: "brutal",
  bugbear: "bugbear",
  bulwark: "bastiao",
  caligni: "caligni",
  cantrip: "truque",
  "capacity-3": "capacidade-3",
  "capacity-5": "capacidade-5",
  catfolk: "felido",
  celestial: "celestial",
  centaur: "centauro",
  champion: "campeão",
  changeling: "changeling",
  circus: "circo",
  class: "classe",
  cleric: "clérigo",
  cold: "frio",
  "cold-iron": "ferro-frio",
  comfort: "conforto",
  commander: "comandante",
  composite: "composto",
  composition: "composição",
  concealable: "ocultável",
  concentrate: "concentração",
  concussive: "concussivo",
  conrasu: "conrasu",
  consecration: "consagração",
  construct: "constructo",
  consumable: "consumível",
  contingency: "contingência",
  couatl: "couatl",
  curse: "maldição",
  cursebound: "atado-à-maldição",
  cursed: "amaldicoado",
  daemon: "daemon",
  darkness: "escuridão",
  "deadly-2d10": "letal-2d10",
  "deadly-2d12": "letal-2d12",
  "deadly-2d8": "letal-2d8",
  "deadly-3d10": "letal-3d10",
  "deadly-3d12": "letal-3d12",
  "deadly-d10": "letal-d10",
  "deadly-d12": "letal-d12",
  "deadly-d6": "letal-d6",
  "deadly-d8": "letal-d8",
  death: "morte",
  dedication: "dedicação",
  demon: "demonio",
  dero: "dero",
  detection: "detecção",
  devil: "diabo",
  dhampir: "dampiro",
  dinosaur: "dinossauro",
  disarm: "desarmar",
  disease: "doença",
  divine: "divino",
  "double-barrel": "cano-duplo",
  downtime: "tempo-livre",
  dragon: "dragao",
  dragonblood: "sangue-de-dragao",
  dragonet: "dragonete",
  dromaar: "dromaar",
  druid: "druida",
  duergar: "duergar",
  duskwalker: "caminhante-do-crepusculo",
  dwarf: "anão",
  earth: "terra",
  eidolon: "eidolon",
  electricity: "eletricidade",
  elemental: "elemental",
  elf: "elfo",
  emotion: "emoção",
  esoterica: "esotérica",
  ethereal: "etereo",
  evil: "maligno",
  exemplar: "exemplar",
  exploration: "exploração",
  extradimensional: "extradimensional",
  "fatal-d10": "fatal-d10",
  "fatal-d12": "fatal-d12",
  "fatal-d8": "fatal-d8",
  fear: "medo",
  fey: "fada",
  fiend: "corrupto",
  fighter: "guerreiro",
  finesse: "precisão",
  finisher: "finalização",
  fire: "fogo",
  fleshwarp: "disforme",
  flexible: "flexível",
  flourish: "floreio",
  focus: "foco",
  force: "força",
  forceful: "vigoroso",
  fortune: "sorte",
  "free-hand": "mao-livre",
  fungus: "fungo",
  general: "geral",
  genie: "genio",
  ghoran: "ghoran",
  ghost: "fantasma",
  ghoul: "carnical",
  giant: "gigante",
  gnome: "gnomo",
  goblin: "goblin",
  goloma: "goloma",
  good: "benigno",
  graveknight: "graveknight",
  gremlin: "gremlin",
  guardian: "guardião",
  gunslinger: "pistoleiro",
  hag: "megera",
  halfling: "halfling",
  healing: "cura",
  hex: "bruxaria",
  hobgoblin: "hobgoblin",
  holy: "sagrado",
  human: "humano",
  humanoid: "humanoide",
  illusion: "ilusão",
  impulse: "impulso",
  incapacitation: "incapacitação",
  incarnate: "encarnado",
  incorporeal: "incorporeo",
  infusion: "infusão",
  injury: "ferimento",
  inventor: "inventor",
  invested: "investido",
  investigator: "investigador",
  jotunborn: "jotunborn",
  "jousting-d6": "justa-d6",
  kholo: "kholo",
  kickback: "coice",
  kineticist: "cineticista",
  kobold: "kobold",
  leshy: "leshy",
  light: "luz",
  lineage: "linhagem",
  linguistic: "linguístico",
  lizardfolk: "reptiliano",
  locathah: "locathah",
  magical: "mágico",
  magus: "magus",
  manipulate: "manipulação",
  mental: "mental",
  merfolk: "merfolk",
  metal: "metal",
  mindless: "sem-mente",
  mindshift: "mudança-mental",
  minotaur: "minotauro",
  misfortune: "azar",
  modular: "modular",
  monitor: "monitor",
  monk: "monge",
  morph: "metamorfose",
  move: "movimento",
  multiclass: "multiclasse",
  mummy: "mumia",
  mutant: "mutante",
  mythic: "mítico",
  naari: "naari",
  nephilim: "nefilim",
  noisy: "barulhento",
  nonlethal: "não-letal",
  nymph: "ninfa",
  oath: "voto",
  occult: "oculto",
  olfactory: "olfativo",
  oni: "oni",
  ooze: "limo",
  oracle: "oráculo",
  orc: "orc",
  oread: "oréade",
  overflow: "transbordamento",
  parry: "aparar",
  phantom: "fantasma",
  plant: "planta",
  poison: "veneno",
  polymorph: "transmutação",
  poppet: "marionete",
  possession: "possessao",
  potion: "poção",
  prediction: "previsão",
  press: "pressão",
  primal: "primal",
  propulsive: "propulsivo",
  protean: "proteano",
  psyche: "psique",
  psychic: "psíquico",
  psychopomp: "psicopompo",
  qlippoth: "qlippoth",
  rage: "fúria",
  rakshasa: "rakshasa",
  "ranged-trip": "derrubar-a-distancia",
  ranger: "patrulheiro",
  ratfolk: "ratkin",
  razing: "arrasador",
  reach: "alcance",
  "reach-0": "alcance-0",
  "reach-10": "alcance-10",
  "reach-100": "alcance-100",
  "reach-15": "alcance-15",
  "reach-20": "alcance-20",
  "reach-25": "alcance-25",
  "reach-30": "alcance-30",
  "reach-40": "alcance-40",
  "reach-60": "alcance-60",
  reckless: "imprudente",
  "reload-0": "recarga-0",
  "reload-1": "recarga-1",
  "reload-2": "recarga-2",
  repeating: "repetição",
  revelation: "revelação",
  rogue: "ladino",
  samsaran: "samsaran",
  sanctified: "santificado",
  sarangay: "sarangay",
  "scatter-10": "dispersão-10",
  scroll: "pergaminho",
  scrying: "vidência",
  secret: "secreto",
  sedacthy: "sedacthy",
  serpentfolk: "serpentfolk",
  shadow: "sombra",
  shisk: "shisk",
  shoony: "shoony",
  shove: "empurrar",
  skeleton: "esqueleto",
  skill: "perícia",
  sleep: "sono",
  social: "social",
  sonic: "sônico",
  sorcerer: "feiticeiro",
  soulbound: "ligado-a-alma",
  spellshape: "moldar-magia",
  spellshot: "tiro-magico",
  spirit: "espírito",
  splash: "respingo",
  sprite: "sprite",
  staff: "cajado",
  stamina: "vigor",
  stance: "postura",
  strix: "strix",
  structure: "estrutura",
  subtle: "sutil",
  suli: "suli",
  summon: "convocação",
  summoner: "conjurador",
  swarm: "enxame",
  swashbuckler: "espadachim",
  sweep: "varredura",
  sylph: "sílfide",
  tactic: "tática",
  talisman: "talismã",
  talos: "talos",
  tandem: "conjunto",
  tane: "tane",
  teleportation: "teleporte",
  tengu: "tengu",
  thaumaturge: "taumaturgo",
  thrown: "arremesso",
  "thrown-10": "arremesso-10",
  "thrown-100": "arremesso-100",
  "thrown-20": "arremesso-20",
  "thrown-30": "arremesso-30",
  transcendence: "transcendência",
  trip: "derrubar",
  tripkee: "tripkee",
  troll: "troll",
  "true-name": "nome-verdadeiro",
  "two-hand-d10": "duas-maos-d10",
  "two-hand-d12": "duas-mãos-d12",
  "two-hand-d8": "duas-mãos-d8",
  unarmed: "desarmado",
  undead: "morto-vivo",
  undine: "ondina",
  unholy: "profano",
  unstable: "instável",
  vampire: "vampiro",
  "versatile-b": "versatil-b",
  "versatile-p": "versátil-p",
  "versatile-s": "versátil-c",
  virulent: "virulento",
  visual: "visual",
  vitality: "vitalidade",
  void: "vazio",
  "volley-20": "salva-20",
  "volley-30": "salva-30",
  water: "água",
  werecreature: "licantropo",
  wight: "wight",
  witch: "bruxo",
  wizard: "mago",
  wood: "madeira",
  wraith: "espectro",
  xulgath: "xulgath",
  zombie: "zumbi",
});

/**
 * Damage-type slug → pt-BR.
 */
export const DAMAGE_TYPE_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  acid: "ácido",
  bleed: "sangramento",
  bludgeoning: "concussão",
  cold: "frio",
  electricity: "eletricidade",
  fire: "fogo",
  force: "força",
  mental: "mental",
  piercing: "perfuração",
  poison: "veneno",
  precision: "precisão",
  slashing: "corte",
  sonic: "sônico",
  spirit: "espírito",
  untyped: "sem tipo",
  vitality: "vitalidade",
  void: "vazio",
});

/**
 * Magic tradition slug → pt-BR.
 */
export const TRADITION_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  arcane: "Arcana",
  divine: "Divina",
  occult: "Oculta",
  primal: "Primal",
});

/**
 * Rarity slug → pt-BR.
 */
export const RARITY_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  common: "Comum",
  rare: "Raro",
  uncommon: "Incomum",
  unique: "Único",
});

/**
 * Area-template shape slug → pt-BR.
 */
export const AREA_SHAPE_NAMES_PT: Readonly<Record<string, string>> = Object.freeze({
  burst: "explosão",
  cone: "cone",
  cube: "cubo",
  cylinder: "cilindro",
  emanation: "emanação",
  line: "linha",
  square: "quadrado",
});
