/**
 * normalize-rules.test.mjs — tests for the deterministic ChoiceSet/GrantItem
 * normalizer (normalize-rules.mjs), against REAL doc fixtures pulled from
 * systems/pf2e/packs/feats-core/documents.json (see fixtures/feats-core-samples.json,
 * generated by a one-off script and pinned as a fixture — pipeline logic
 * must keep working even if the live pack docs later change/get removed).
 *
 * These are exactly the four calibration cases named in the T1 design
 * contract §3.c mapping table.
 *
 * Owner: implementer A (pipeline). Runs under `node --test`.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { normalizeDocMechanics } from "../normalize-rules.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "feats-core-samples.json"), "utf8"),
);

test("Basic Concoction -> grant {category: class, trait: alchemist, maxLevel: 2}, confidence 1.0", () => {
  const { grants, unlocks } = normalizeDocMechanics(fixtures["Basic Concoction"]);
  assert.equal(unlocks.length, 0);
  assert.equal(grants.length, 1);
  const grant = grants[0];
  assert.equal(grant.kind, "feat-choice");
  assert.equal(grant.category, "class");
  assert.deepEqual(grant.filters.traits, ["alchemist"]);
  assert.equal(grant.filters.maxLevel, 2);
  assert.equal(grant.count, 1);
  assert.equal(grant.source, "rule-element");
  assert.equal(grant.confidence, 1.0);
});

test("Ancestral Paragon -> grant {category: ancestry, levelExpr literal}, confidence < 1.0 (dynamic traits)", () => {
  const { grants, unlocks } = normalizeDocMechanics(fixtures["Ancestral Paragon"]);
  assert.equal(unlocks.length, 0);
  assert.equal(grants.length, 1);
  const grant = grants[0];
  assert.equal(grant.kind, "feat-choice");
  assert.equal(grant.category, "ancestry");
  assert.equal(grant.filters.levelExpr, "item:level:1");
  // Dynamic {actor|...} trait predicates must NOT leak into filters.traits.
  assert.equal(grant.filters.traits, undefined);
  assert.equal(grant.source, "rule-element");
  assert.ok(grant.confidence < 1.0, "confidence must be reduced for non-literal predicates");
});

test("Adopted Ancestry -> unlock {mechanism: adopted-ancestry, excludeOwnAncestry: true}, no grants", () => {
  const { grants, unlocks } = normalizeDocMechanics(fixtures["Adopted Ancestry"]);
  assert.equal(grants.length, 0);
  assert.equal(unlocks.length, 1);
  const unlock = unlocks[0];
  assert.equal(unlock.kind, "ancestry-feat-eligibility");
  assert.equal(unlock.mechanism, "adopted-ancestry");
  assert.equal(unlock.filters.excludeOwnAncestry, true);
  assert.equal(unlock.source, "rule-element");
  assert.equal(unlock.confidence, 1.0);
});

test("Alchemist Dedication -> no grants, no unlocks (fixed grant-item targets, not a ChoiceSet choice)", () => {
  const { grants, unlocks } = normalizeDocMechanics(fixtures["Alchemist Dedication"]);
  assert.equal(grants.length, 0);
  assert.equal(unlocks.length, 0);
});

test("Terrain Stalker (array-type ChoiceSet: static terrain picklist) -> ignored, no grants/unlocks", () => {
  const { grants, unlocks } = normalizeDocMechanics(fixtures["Terrain Stalker"]);
  assert.equal(grants.length, 0);
  assert.equal(unlocks.length, 0);
});

test("normalizeDocMechanics tolerates docs with no rules/flags at all", () => {
  assert.doesNotThrow(() => normalizeDocMechanics({}));
  assert.doesNotThrow(() => normalizeDocMechanics({ system: {} }));
  const { grants, unlocks } = normalizeDocMechanics({ name: "Empty Doc" });
  assert.deepEqual(grants, []);
  assert.deepEqual(unlocks, []);
});

test("a ChoiceSet(feat) without a paired grant-item produces no grant", () => {
  const doc = {
    _id: "fakeDoc1",
    name: "Fake Unpaired Feat",
    system: { rules: [] },
    flags: {
      fusion: {
        unconvertedRules: [
          {
            key: "ChoiceSet",
            flag: "someFlag",
            choices: { itemType: "feat", filter: ["item:category:class"] },
          },
        ],
      },
    },
  };
  const { grants, unlocks } = normalizeDocMechanics(doc);
  assert.equal(grants.length, 0);
  assert.equal(unlocks.length, 0);
});
